#!/usr/bin/env python3
from reddit  import create as create_reddit
from twitter import create as create_twitter

from sources import get_sources

reddit_bot  = create_reddit()
twitter_bot = create_twitter()

sources = get_sources()
print(sources)

